{
 "title": "Dashboard 3 — Custom Exporter (External APIs)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "City",
    "query": {
     "query": "label_values(external_weather_temperature_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Exchange Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    (external_currency_usd_kzt + external_currency_eur_kzt + external_currency_rub_kzt) / 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EUR to KZT Exchange Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "   external_currency_eur_kzt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "USD to KZT Exchange Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "   external_currency_usd_kzt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cloud Coverage (sum)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "   sum(external_weather_clouds_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed by City",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "   external_weather_wind_speed_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed by City",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "   avg(external_weather_wind_speed_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity by City (grouped)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "   sum(external_weather_humidity_percent) by (city)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Humidity Across All Cities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "   avg(external_weather_humidity_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature by City",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "   external_weather_temperature_celsius",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Temperature Across All Cities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "   avg(external_weather_temperature_celsius)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}