set -euo pipefail


PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv_superset"

ensure_venv() {
    if [ ! -d "$VENV_DIR" ]; then
        python3 -m venv "$VENV_DIR"
    fi
    source "$VENV_DIR/bin/activate"
    python -m pip install --upgrade pip setuptools wheel
}

ensure_superset_config() {
    local cfg_file="$PROJECT_DIR/superset_config.py"
    if [ ! -f "$cfg_file" ]; then
        local secret
        if command -v openssl >/dev/null 2>&1; then
            secret=$(openssl rand -base64 42 | tr -d '\n')
        else
            secret=$(python - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
)
        fi
        cat > "$cfg_file" <<EOF
# Generated by superset_setup.sh
SECRET_KEY = "${secret}"
# Use a local SQLite DB by default; adjust if you want Postgres/MySQL
SQLALCHEMY_DATABASE_URI = f"sqlite:///${PROJECT_DIR}/superset.db"
EOF
        echo "Created $cfg_file with a secure SECRET_KEY"
    fi
    export SUPERSET_CONFIG_PATH="$cfg_file"
}

cmd_install() {
    ensure_venv
    ensure_superset_config
    pip install "apache-superset==4.0.2" "psycopg2-binary==2.9.9" "sqlalchemy==1.4.52"
    pip install "marshmallow==3.21.1"
    pip install "Flask-Limiter==2.9.0" "rich==12.6.0" "commonmark==0.9.1"

    export FLASK_APP=superset
    superset db upgrade
    if ! superset fab list-users | grep -q "\badmin\b"; then
        superset fab create-admin \
          --username admin \
          --firstname Admin \
          --lastname User \
          --email admin@example.com \
          --password admin
    fi
    superset init
    echo "Installation and initialization complete. Run: bash superset_setup.sh start"
}

cmd_start() {
    ensure_venv
    ensure_superset_config
    export FLASK_APP=superset
    nohup superset run -h 0.0.0.0 -p 8088 > "$PROJECT_DIR/superset_web.log" 2>&1 & echo $! > "$PROJECT_DIR/superset_web.pid"
    echo "Superset running at http://localhost:8088 (PID $(cat "$PROJECT_DIR/superset_web.pid"))"
}

cmd_stop() {
    for pidfile in "$PROJECT_DIR"/superset_*.pid; do
        [ -e "$pidfile" ] || continue
        pid=$(cat "$pidfile")
        if kill -0 "$pid" 2>/dev/null; then
            kill "$pid" || true
            echo "Stopped $(basename "$pidfile") (PID $pid)"
        fi
        rm -f "$pidfile"
    done
}

cmd_create_admin() {
    ensure_venv
    export FLASK_APP=superset
    user="$1"; email="$2"; pass="${3:-admin}"
    superset fab create-admin --username "$user" --firstname "$user" --lastname User --email "$email" --password "$pass"
}

main() {
    subcmd="${1:-}"
    case "$subcmd" in
        install) shift; cmd_install "$@" ;;
        start) shift; cmd_start "$@" ;;
        stop) shift; cmd_stop "$@" ;;
        create-admin) shift; cmd_create_admin "$@" ;;
        *)
            cat <<EOF
Usage: bash superset_setup.sh <install|start|stop|create-admin>
EOF
            exit 1
            ;;
    esac
}

main "$@"
